[문제2] try-catch-finally 블록에 대한 설명 중 틀린 것은?
정답: 3번
해설: finally 블록은 무조건 실행된다.
1) try {} 블록에는 예외가 발생할 수 있는 코드를 작성한다.
2) catch {} 블록은 try {} 블록에서 발생한 예외를 처리하는 블록이다.
3) try {} 블록에서 return문을 사용하면 finally {} 블록은 실행되지 않는다.
4) catch {} 블록은 예외의 종류별로 여러 개를 작성할 수 있다.